Bulk upload excelsheet
tsprasath/knowledge-platform pull request #4
Opened 2023-04-18 06:16 UTC by ReshmaPrasad97

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java 11, scala-2.11, play-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-18 12:43 UTC, shishirsuman092 requested changes

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/CompetencyExcelParser.scala
> +  /*def getCompetenciesData1(sheet: XSSFSheet): List[util.Map[String, AnyRef]] = {
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/CompetencyExcelParser.scala
> +           // if (index ==1) {
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/CompetencyExcelParser.scala
> +    val columnIdx = if (sheet.getWorkbook.getSheetIndex(sheet) == 1 || sheet.getWorkbook.getSheetIndex(sheet) == 8) 4 else 5
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/CompetencyExcelParser.scala
> +    /* val column = sheet.asScala.drop(1).map(row =>
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/QuestionExcelParser.scala
> +        board = "GNM"
remove hard coded strings, put them in constants

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/QuestionExcelParser.scala
> +      //      val option = o.split("[//)]").toList
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
> +        // CompetencyExcelParser.getExcelData(absolutePath.toFile)
remove commented code

2023-04-18 12:43 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
> +      //val body = requestBody()
remove commented code

2023-04-19 04:10 UTC, shishirsuman092 requested changes

2023-04-19 04:10 UTC, shishirsuman092 commented on assessment-api/assessment-service/conf/application.conf
> +objectcategorydefinition.keyspace="dev_category_store"
remove this change. This is a local change and it will not go as part of the commit

2023-04-19 04:10 UTC, shishirsuman092 commented on assessment-api/assessment-service/conf/application.conf
> +  keyspace = "dev_question_store"
remove this change. This is a local change and it will not go as part of the commit

2023-04-19 04:10 UTC, shishirsuman092 commented on assessment-api/assessment-service/conf/application.conf
> +questionset.keyspace="dev_hierarchy_store"
remove this change. This is a local change and it will not go as part of the commit

2023-04-19 04:10 UTC, shishirsuman092 commented on assessment-api/assessment-service/app/handlers/QuestionExcelParser.scala
> +    setArrayValue(question, difficultyLevel, "difficultyLevel")
define strings in constants file

2023-04-20 18:28 UTC, ReshmaPrasad97 commented on assessment-api/assessment-service/app/handlers/QuestionExcelParser.scala
> +    setArrayValue(question, difficultyLevel, "difficultyLevel")
issue resolved

2023-04-20 18:28 UTC, ReshmaPrasad97 commented on assessment-api/assessment-service/conf/application.conf
> +questionset.keyspace="dev_hierarchy_store"
issue resolved

2023-04-20 18:28 UTC, ReshmaPrasad97 commented on assessment-api/assessment-service/app/controllers/v4/QuestionController.scala
> +      //val body = requestBody()
issue resolved

2023-04-27 07:24 UTC, rahulbowade approved these changes
Approved

2023-04-27 07:33 UTC, shishirsuman092 approved these changes
reviewed

2023-04-27 07:34 UTC, merged